/* =========================================================
   SANDEEP ELECTROFIX - ESTIMATE LIST
   UI + app logic. Master material data stays in material.js.
   ========================================================= */
'use strict';
(() => {
  const $ = (s, root = document) => root.querySelector(s);
  const $$ = (s, root = document) => [...root.querySelectorAll(s)];
  const cfg = window.APP_CONFIG || {};
  const keys = cfg.storageKeys || {};
  const STORE = {
    lang: keys.language || 'sandeepMaterialLang', theme: keys.theme || 'sandeepTheme',
    items: keys.items || 'sandeepEstimateItems', route: keys.lastView || 'sandeepEstimateRoute',
    stage: keys.stage || 'sandeepLastStage', section: keys.section || 'sandeepLastSection'
  };
  const translations = {
    hi: {
      tagline:'आपके विश्वास को रोशन करते हुए',welcome:'आपका स्वागत है',subtitle:'आपका स्मार्ट इलेक्ट्रिकल एस्टिमेट टूल',stages:'स्टेज',estimate:'एस्टिमेट',estimateList:'एस्टिमेट लिस्ट',calculator:'कैलकुलेटर',settings:'सेटिंग्स',projectStages:'प्रोजेक्ट के चरण',fiveStages:'पाँच चरण – एस्टिमेट लिस्ट',stageSection:'स्टेज / सेक्शन',materialDetails:'सामग्री का विवरण',clear:'साफ़ करें',addToEstimate:'एस्टिमेट में जोड़ें',yourMaterials:'आपकी सामग्री',estimatedTotal:'अनुमानित कुल राशि',clearAll:'सब हटाएँ',electricalTools:'इलेक्ट्रिकल टूल्स',powerCalc:'पावर',ohmsLaw:'वोल्टेज / करंट',inverter:'इन्वर्टर',voltage:'वोल्टेज (V)',current:'करंट (A)',powerWatts:'पावर (W)',batteryVoltage:'बैटरी वोल्टेज',loadWatts:'लोड (W)',calcHint:'यह आदर्श गणना है; इन्वर्टर लॉस और सुरक्षा मार्जिन अलग से जोड़ें।',personalize:'अपनी पसंद',language:'भाषा',languageHint:'एक समय में एक भाषा',appearance:'थीम',appearanceHint:'अपनी पसंद चुनें',dark:'डार्क',light:'लाइट',resetApp:'ऐप रीसेट करें',about:'ऐप के बारे में',filter:'फ़िल्टर',chooseStage:'स्टेज चुनें',chooseSection:'सेक्शन चुनें',reset:'रीसेट',apply:'लागू करें',home:'होम',search:'सामग्री खोजें…',noStages:'material.js में स्टेज डेटा नहीं मिला।',noSections:'इस स्टेज में सेक्शन नहीं मिला।',noMaterials:'इस सेक्शन में सामग्री नहीं मिली।',emptyEstimate:'अभी एस्टिमेट खाली है',emptyEstimateHint:'सामग्री जोड़ने के लिए स्टेज से कोई आइटम चुनें।',qty:'मात्रा',unit:'यूनिट',brand:'ब्रांड',price:'प्रति यूनिट कीमत (वैकल्पिक)',size:'साइज़',type:'टाइप',required:'यह फ़ील्ड ज़रूरी है।',added:'सामग्री एस्टिमेट में जोड़ दी गई।',updated:'एस्टिमेट अपडेट हो गया।',cleared:'फ़ॉर्म साफ़ कर दिया गया।',confirmClear:'क्या आप पूरी एस्टिमेट लिस्ट हटाना चाहते हैं?',confirmReset:'ऐप की सेटिंग्स और एस्टिमेट रीसेट करें?',resetDone:'ऐप रीसेट हो गया।',aboutText:'Sandeep ElectroFix — Electrical Services, Lucknow.',deleted:'आइटम हटा दिया गया।',edit:'एडिट करें',delete:'हटाएँ',select:'चुनें',noPrice:'कीमत नहीं दी गई',allStages:'सभी स्टेज',allSections:'सभी सेक्शन',filterApplied:'फ़िल्टर लागू हो गया।',exported:'एस्टिमेट टेक्स्ट कॉपी/शेयर के लिए तैयार है।',exportTitle:'SANDEEP ELECTROFIX — ESTIMATE',stage:'स्टेज',section:'सेक्शन',material:'सामग्री',amount:'राशि',userInput:'अपनी वैल्यू लिखें',noResults:'कोई परिणाम नहीं मिला।'
    },
    en: {
      tagline:'Powering Your Trust',welcome:'WELCOME TO',subtitle:'Your smart electrical estimate tool',stages:'Stages',estimate:'Estimate',estimateList:'Estimate List',calculator:'Calculator',settings:'Settings',projectStages:'PROJECT FLOW',fiveStages:'Five stages — estimate list',stageSection:'STAGE / SECTION',materialDetails:'MATERIAL DETAILS',clear:'Clear',addToEstimate:'Add to Estimate',yourMaterials:'YOUR MATERIALS',estimatedTotal:'Estimated total',clearAll:'Clear all',electricalTools:'ELECTRICAL TOOLS',powerCalc:'Power',ohmsLaw:'Voltage / Current',inverter:'Inverter',voltage:'Voltage (V)',current:'Current (A)',powerWatts:'Power (W)',batteryVoltage:'Battery voltage',loadWatts:'Load (W)',calcHint:'Ideal calculation only; add inverter losses and a safety margin separately.',personalize:'PERSONALIZE',language:'Language',languageHint:'One language at a time',appearance:'Theme',appearanceHint:'Choose your preference',dark:'Dark',light:'Light',resetApp:'Reset app',about:'About the app',filter:'Filter',chooseStage:'Choose stage',chooseSection:'Choose section',reset:'Reset',apply:'Apply',home:'Home',search:'Search materials…',noStages:'No stage data found in material.js.',noSections:'No sections found in this stage.',noMaterials:'No materials found in this section.',emptyEstimate:'Your estimate is empty',emptyEstimateHint:'Choose an item from a stage to add material.',qty:'Quantity',unit:'Unit',brand:'Brand',price:'Unit price (optional)',size:'Size',type:'Type',required:'This field is required.',added:'Material added to estimate.',updated:'Estimate item updated.',cleared:'Form cleared.',confirmClear:'Remove all items from this estimate?',confirmReset:'Reset app settings and estimate list?',resetDone:'App has been reset.',aboutText:'Sandeep ElectroFix — Electrical Services, Lucknow.',deleted:'Item removed.',edit:'Edit',delete:'Delete',select:'Select',noPrice:'No price entered',allStages:'All stages',allSections:'All sections',filterApplied:'Filter applied.',exported:'Estimate text is ready to share.',exportTitle:'SANDEEP ELECTROFIX — ESTIMATE',stage:'Stage',section:'Section',material:'Material',amount:'Amount',userInput:'Enter a value',noResults:'No results found.'
    }
  };
  const hiNames = {
    'Slab Conduit Installation':'स्लैब कंड्यूट इंस्टॉलेशन','Wall Conduit Installation':'वॉल कंड्यूट इंस्टॉलेशन','Wiring Installation':'वायरिंग इंस्टॉलेशन','Final Electrical Fittings':'फाइनल इलेक्ट्रिकल फिटिंग्स','False Ceiling Wiring Material':'फॉल्स सीलिंग वायरिंग मटेरियल',
    'Conduit & Box':'कंड्यूट और बॉक्स','Installation Material':'इंस्टॉलेशन मटेरियल','Pulling Material':'पुलिंग मटेरियल','Switch & Socket':'स्विच और सॉकेट','MCB & Protection':'MCB और प्रोटेक्शन','Fan & Ceiling':'फैन और सीलिंग','Lighting':'लाइटिंग','Installation & Finishing':'इंस्टॉलेशन और फिनिशिंग','Wiring Material':'वायरिंग मटेरियल','Wiring & Conduit':'वायरिंग और कंड्यूट','Installation & Fastening':'इंस्टॉलेशन और फास्टनिंग',
    'Pipe':'पाइप','Bend':'बेंड','Junction Box':'जंक्शन बॉक्स','Fan Box':'फैन बॉक्स','Concealed Light Box':'कंसील्ड लाइट बॉक्स','Tape (Shuttering & Joint Sealing)':'टेप (शटरिंग और जॉइंट सीलिंग)','Solvent Cement':'सॉल्वेंट सीमेंट','Neel Powder (Marking Powder)':'नील पाउडर','Binding Wire':'बाइंडिंग वायर','Cable Tie / Zip Tie':'केबल टाई / ज़िप टाई','Modular Board (Concealed Metal/PVC Box)':'मॉड्यूलर बोर्ड','MCB Box (Distribution Board)':'MCB बॉक्स (डिस्ट्रीब्यूशन बोर्ड)','Tape (Masking & Plaster Protection)':'टेप (मास्किंग और प्लास्टर प्रोटेक्शन)','Cable Clip':'केबल क्लिप','Wire':'वायर','Flexible Pipe':'फ्लेक्सिबल पाइप','Electrical Tape':'इलेक्ट्रिकल टेप','Fastener':'फास्टनर','Steel Wire / Spring Wire (Fish Tape)':'स्टील वायर / फिश टेप','Switch Plate':'स्विच प्लेट','Switch Board (Surface Gang Box)':'स्विच बोर्ड','Switch':'स्विच','Socket':'सॉकेट','Fan Regulator':'फैन रेगुलेटर','2 Way Switch':'2 वे स्विच','Bell Push':'बेल पुश','Neon Indicator':'नियॉन इंडिकेटर','Blank Plate / Dummy Switch':'ब्लैंक प्लेट / डमी स्विच','DP Switch (Double Pole Switch)':'DP स्विच','Mini MCB':'मिनी MCB','SP MCB (Single Pole)':'SP MCB','DP MCB (Double Pole)':'DP MCB','TPN MCB (Three Pole with Neutral)':'TPN MCB','MCB Changeover':'MCB चेंजओवर','DP Isolator':'DP आइसोलेटर','TPN Isolator (3P / 4P)':'TPN आइसोलेटर','RCCB / RCD':'RCCB / RCD','Kit Kat Fuse':'किट कैट फ्यूज','Fan Sheet':'फैन शीट','Round Sheet':'राउंड शीट','Fan Rod':'फैन रॉड','Fan Clamp':'फैन क्लैंप','Holder':'होल्डर','Ceiling Rose':'सीलिंग रोज़','Chain':'चेन','LED Bulb':'LED बल्ब','LED Tube Light':'LED ट्यूब लाइट','Foot Light':'फुट लाइट','Up Down Light':'अप डाउन लाइट','Panel Light':'पैनल लाइट','Surface Light':'सरफेस लाइट','COB Light':'COB लाइट','COB Spot Light':'COB स्पॉट लाइट','Down Light':'डाउन लाइट','Strip Light':'स्ट्रिप लाइट','Rope Light':'रोप लाइट','LED Profile Channel':'LED प्रोफाइल चैनल','LED Strip Driver (SMPS)':'LED स्ट्रिप ड्राइवर (SMPS)','Door Bell':'डोर बेल','Tape (Mounting / Double Sided)':'माउंटिंग / डबल साइडेड टेप','Instant Glue':'इंस्टेंट ग्लू','Araldite Glue (Epoxy)':'अराल्डाइट ग्लू (एपॉक्सी)','POP (Plaster of Paris)':'POP (प्लास्टर ऑफ पेरिस)','Putty Blade / Patta':'पुट्टी ब्लेड / पट्टा','Screw':'स्क्रू','Lug (Cable Terminal Lug)':'लग (केबल टर्मिनल लग)','Washer':'वॉशर','PVC Wall Plug / Gulli / Gitti':'PVC वॉल प्लग / गुल्ली / गिट्टी','Saddle (Pipe Clamp)':'सैडल (पाइप क्लैंप)'
  };
  let lang = localStorage.getItem(STORE.lang) || 'hi';
  let theme = localStorage.getItem(STORE.theme) || 'dark';
  let estimate = safeJSON(localStorage.getItem(STORE.items), []);
  let stages = [], currentStage = null, currentSection = null, currentMaterial = null, editingId = null, routeStack = ['home'];
  let filter = {stage:'all',section:'all'};
  const views = {home:'homeView',stages:'stageView',sections:'stageView',materials:'materialsView',editor:'editorView',estimate:'estimateView',calculator:'calculatorView',settings:'settingsView'};
  function safeJSON(s, fallback){try{return s?JSON.parse(s):fallback}catch{return fallback}}
  function t(k){return (translations[lang]&&translations[lang][k])||translations.en[k]||k}
  function localized(name){return lang==='hi'?(hiNames[name]||name):name}
  function stageName(stage){return `${stage.label} · ${localized(stage.name)}`}
  function save(){localStorage.setItem(STORE.items,JSON.stringify(estimate));updateEstimateBadge()}
  function showToast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.classList.remove('show'),2400)}
  function setLanguage(next){lang=next;localStorage.setItem(STORE.lang,lang);document.documentElement.lang=lang;applyLanguage();renderAll();updateSettingsButtons()}
  function applyLanguage(){ $$('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(translations[lang][key])el.textContent=t(key)}); $$('[data-placeholder-hi]').forEach(el=>el.placeholder=lang==='hi'?el.dataset.placeholderHi:el.dataset.placeholderEn); $('#homeSearch').placeholder=t('search'); $('#materialSearch').placeholder=lang==='hi'?'सामग्री खोजें…':'Search materials…'; $('#estimateSearch').placeholder=lang==='hi'?'एस्टिमेट में खोजें…':'Search estimate…'; }
  function setTheme(next){theme=next;document.body.classList.toggle('light-theme',theme==='light');localStorage.setItem(STORE.theme,theme);$('#themeQuick').textContent=theme==='dark'?'☾':'☀';updateSettingsButtons()}
  function updateSettingsButtons(){ $$('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang)); $$('[data-theme]').forEach(b=>b.classList.toggle('active',b.dataset.theme===theme)) }
  function normalizeData(){
    const raw=window.MATERIALS;
    if(!Array.isArray(raw)){stages=[];return}
    stages=raw.map((s,si)=>{
      if(!Array.isArray(s))return null;
      const stage={id:`s${si+1}`,label:String(s[0]||`STAGE ${si+1}`),name:String(s[1]||`Stage ${si+1}`),sections:[]};
      if(Array.isArray(s[3])) stage.sections.push({name:String(s[2]||'Materials'),items:s[3].filter(Array.isArray)});
      if(Array.isArray(s[4])) s[4].forEach(sec=>{if(Array.isArray(sec)&&Array.isArray(sec[1]))stage.sections.push({name:String(sec[0]||'Materials'),items:sec[1].filter(Array.isArray)})});
      stage.sections=stage.sections.filter(sec=>sec.items.length);
      return stage;
    }).filter(Boolean);
  }
  function go(view,push=true){if(!views[view])view='home';$$('.view').forEach(v=>v.classList.remove('active'));$('#'+views[view]).classList.add('active');$$('.bottom-nav [data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===view||(view==='stages'||view==='sections'||view==='materials'||view==='editor')&&b.dataset.go==='home'));if(push&&routeStack[routeStack.length-1]!==view)routeStack.push(view);localStorage.setItem(STORE.route,view);closeDrawer();window.scrollTo({top:0,behavior:'smooth'});if(view==='estimate')renderEstimate();if(view==='settings')updateSettingsButtons()}
  function back(){if($('#drawer').classList.contains('open')){closeDrawer();return}if($('#filterModal').classList.contains('show')){closeFilter();return}if(routeStack.length>1){routeStack.pop();const previous=routeStack[routeStack.length-1];go(previous,false)}else go('home',false)}
  function renderAll(){renderStages();renderEstimate();if(currentStage)renderSections();if(currentSection)renderMaterials();applyLanguage()}
  function renderStages(){const host=$('#stageCards');host.innerHTML='';$('#stageCount').textContent=String(stages.length).padStart(2,'0');if(!stages.length){host.innerHTML=`<div class="empty-state"><strong>${t('noStages')}</strong><small>Keep your supplied master list in a file named material.js.</small></div>`;return}stages.forEach((s,i)=>{const total=s.sections.reduce((n,sec)=>n+sec.items.length,0);const btn=document.createElement('button');btn.className='stage-card';btn.innerHTML=`<span class="stage-number">${i+1}</span><span class="card-copy"><strong>${escapeHTML(localized(s.name))}</strong><small>${escapeHTML(s.sections.map(x=>localized(x.name)).join(' · '))} · ${total} ${lang==='hi'?'आइटम':'items'}</small></span><span class="card-arrow">›</span>`;btn.addEventListener('click',()=>openStage(s));host.appendChild(btn)});fillFilterOptions()}
  function openStage(stage){currentStage=stage;localStorage.setItem(STORE.stage,stage.id);$('#stageTitle').textContent=localized(stage.name);renderSections();go('stages')}
  function renderSections(){const host=$('#sectionCards');host.innerHTML='';if(!currentStage)return;if(!currentStage.sections.length){host.innerHTML=`<div class="empty-state">${t('noSections')}</div>`;return}currentStage.sections.forEach((sec,i)=>{const b=document.createElement('button');b.className='section-card';b.innerHTML=`<span class="section-symbol">${i===0?'▱':'⚡'}</span><span class="card-copy"><strong>${escapeHTML(localized(sec.name))}</strong><small>${sec.items.length} ${lang==='hi'?'सामग्री':'materials'}</small></span><span class="card-arrow">›</span>`;b.addEventListener('click',()=>{currentSection=sec;localStorage.setItem(STORE.section,sec.name);$('#materialsTitle').textContent=localized(sec.name);$('#materialKicker').textContent=currentStage.label;renderMaterials();go('materials')});host.appendChild(b)})}
  function renderMaterials(){const host=$('#materialCards');host.innerHTML='';if(!currentSection)return;const query=($('#materialSearch').value||'').trim().toLowerCase();let found=0;currentSection.items.forEach((item,index)=>{const name=String(item[0]||'Material');if(query&&!name.toLowerCase().includes(query)&&!localized(name).toLowerCase().includes(query))return;found++;const b=document.createElement('button');b.className='material-card';const detail=(Array.isArray(item[1])?item[1].map(f=>f[0]).filter(Boolean).slice(0,3).join(' · '):'');b.innerHTML=`<span class="product-icon">${iconFor(name)}</span><span class="card-copy"><strong>${escapeHTML(localized(name))}</strong><small>${escapeHTML(detail)}</small></span><span class="add-circle">＋</span>`;b.addEventListener('click',()=>openEditor(item,index));host.appendChild(b)});if(!found)host.innerHTML=`<div class="empty-state">${t('noResults')}</div>`}
  function iconFor(name){if(/pipe|bend|conduit|saddle/i.test(name))return '▰';if(/light|bulb|led|lamp/i.test(name))return '☼';if(/wire|cable|lug/i.test(name))return '⌁';if(/switch|socket|plate|board/i.test(name))return '▦';if(/mcb|fuse|isolator|rccb/i.test(name))return '⛨';if(/fan|chain|rod|clamp/i.test(name))return '✳';if(/tape|glue|cement|powder/i.test(name))return '▤';return '⚡'}
  function openEditor(item,index){currentMaterial={item,index,stage:currentStage,section:currentSection};editingId=null;$('#editorTitle').textContent=localized(item[0]);$('#editorMaterialName').textContent=localized(item[0]);$('#editorContext').textContent=`${localized(currentStage.name)} · ${localized(currentSection.name)}`;buildForm(item);go('editor')}
  function buildForm(item,existing=null){const form=$('#materialForm');form.innerHTML='';const fields=Array.isArray(item[1])?item[1]:[];fields.forEach((field,i)=>{if(!Array.isArray(field))return;const name=String(field[0]||`Option ${i+1}`),opts=Array.isArray(field[1])?field[1]:[];const label=document.createElement('label');label.className=(fields.length===1?'full':'');const span=document.createElement('span');span.textContent=localized(name);label.appendChild(span);if(opts.some(o=>String(o).startsWith('User Input'))){const input=document.createElement('input');input.type='text';input.name=`option_${i}`;input.placeholder=t('userInput');input.value=existing?.options?.[name]||'';label.appendChild(input)}else{const select=document.createElement('select');select.name=`option_${i}`;const first=document.createElement('option');first.value='';first.textContent=`— ${t('select')} —`;select.appendChild(first);opts.forEach(o=>{const op=document.createElement('option');op.value=String(o);op.textContent=String(o);select.appendChild(op)});select.value=existing?.options?.[name]||'';label.appendChild(select)}form.appendChild(label)});
    const qtyLabel=document.createElement('label');qtyLabel.innerHTML=`<span>${t('qty')} *</span><input name="quantity" type="number" inputmode="decimal" min="0.001" step="any" required placeholder="0" value="${existing?escapeAttr(existing.quantity):''}">`;form.appendChild(qtyLabel);
    const unitLabel=document.createElement('label');unitLabel.innerHTML=`<span>${t('unit')} *</span>`;const unitSel=document.createElement('select');unitSel.name='unit';(Array.isArray(item[2])?item[2]:['pcs']).forEach(u=>{const op=document.createElement('option');op.value=String(u);op.textContent=String(u);unitSel.appendChild(op)});unitSel.value=existing?.unit||unitSel.options[0]?.value||'';unitLabel.appendChild(unitSel);form.appendChild(unitLabel);
    const brandLabel=document.createElement('label');brandLabel.className='full';brandLabel.innerHTML=`<span>${t('brand')} (${lang==='hi'?'वैकल्पिक':'optional'})</span>`;const brandSel=document.createElement('select');brandSel.name='brand';const blank=document.createElement('option');blank.value='';blank.textContent=`— ${t('select')} —`;brandSel.appendChild(blank);(Array.isArray(item[3])?item[3]:[]).forEach(v=>{const op=document.createElement('option');op.value=String(v);op.textContent=String(v);brandSel.appendChild(op)});brandSel.value=existing?.brand||'';brandLabel.appendChild(brandSel);form.appendChild(brandLabel);
    const priceLabel=document.createElement('label');priceLabel.className='price-field';priceLabel.innerHTML=`<span>${t('price')}</span><input name="price" type="number" inputmode="decimal" min="0" step="any" placeholder="₹ 0.00" value="${existing&&existing.price!==null?escapeAttr(existing.price):''}">`;form.appendChild(priceLabel);
    $('#addMaterial').dataset.mode=existing?'edit':'add';$('#addMaterial').innerHTML=existing?`✓ <span>${lang==='hi'?'अपडेट करें':'Update item'}</span>`:`＋ <span>${t('addToEstimate')}</span>`;
  }
  function collectForm(){const form=$('#materialForm');if(!form.reportValidity())return null;const options={};(Array.isArray(currentMaterial.item[1])?currentMaterial.item[1]:[]).forEach((f,i)=>{const el=form.elements[`option_${i}`];if(el&&el.value)options[String(f[0])]=el.value});const q=Number(form.elements.quantity.value);if(!Number.isFinite(q)||q<=0){form.elements.quantity.focus();showToast(t('required'));return null}const priceRaw=form.elements.price.value;return {id:editingId||`${Date.now()}-${Math.random().toString(36).slice(2,7)}`,name:String(currentMaterial.item[0]),stageId:currentMaterial.stage.id,stageName:currentMaterial.stage.name,stageLabel:currentMaterial.stage.label,sectionName:currentMaterial.section.name,options,quantity:q,unit:form.elements.unit.value,brand:form.elements.brand.value,price:priceRaw===''?null:Number(priceRaw),updatedAt:Date.now()}}
  function addOrUpdate(){const data=collectForm();if(!data)return;const idx=estimate.findIndex(x=>x.id===editingId);if(idx>=0){estimate[idx]=data;showToast(t('updated'))}else{estimate.push(data);showToast(t('added'))}save();renderEstimate();$('#materialForm').reset();editingId=null;go('estimate')}
  function renderEstimate(){const host=$('#estimateItems');host.innerHTML='';const query=($('#estimateSearch')?.value||'').trim().toLowerCase();const list=estimate.filter(x=>!query||[x.name,x.stageName,x.sectionName,x.brand,...Object.values(x.options||{})].join(' ').toLowerCase().includes(query));$('#estimateCount').textContent=String(estimate.length);$('#navEstimateCount').textContent=String(estimate.length);let total=0;estimate.forEach(x=>{if(x.price!==null&&Number.isFinite(Number(x.price)))total+=Number(x.price)*Number(x.quantity||0)});$('#grandTotal').textContent=currency(total);if(!list.length){host.innerHTML=`<div class="empty-state"><strong>${t('emptyEstimate')}</strong><span>${t('emptyEstimateHint')}</span></div>`;return}list.forEach(x=>{const realIndex=estimate.findIndex(a=>a.id===x.id);const detail=Object.entries(x.options||{}).map(([k,v])=>`${localized(k)}: ${v}`).join(' · ');const amount=x.price===null?t('noPrice'):currency(Number(x.price)*Number(x.quantity));const card=document.createElement('article');card.className='estimate-item';card.innerHTML=`<span class="estimate-num">${String(realIndex+1).padStart(2,'0')}</span><div class="estimate-details"><strong>${escapeHTML(localized(x.name))}</strong><small>${escapeHTML(localized(x.stageName))} · ${escapeHTML(localized(x.sectionName))}</small><small>${escapeHTML(detail)}${detail?' · ':''}${t('qty')}: ${escapeHTML(x.quantity)} ${escapeHTML(x.unit)}${x.brand?' · '+t('brand')+': '+escapeHTML(x.brand):''}</small><div class="item-price">${escapeHTML(amount)}</div></div><div class="item-tools"><button data-edit="${escapeAttr(x.id)}" aria-label="${t('edit')}">✎</button><button class="delete-item" data-delete="${escapeAttr(x.id)}" aria-label="${t('delete')}">×</button></div>`;host.appendChild(card)});}
  function editEstimateItem(id){const x=estimate.find(a=>a.id===id);if(!x)return;const stage=stages.find(s=>s.id===x.stageId)||stages.find(s=>s.name===x.stageName);if(!stage)return;const section=stage.sections.find(s=>s.name===x.sectionName)||stage.sections[0];const item=section.items.find(a=>String(a[0])===x.name);if(!item)return;currentStage=stage;currentSection=section;currentMaterial={item,index:section.items.indexOf(item),stage,section};editingId=id;$('#editorTitle').textContent=localized(x.name);$('#editorMaterialName').textContent=localized(x.name);$('#editorContext').textContent=`${localized(stage.name)} · ${localized(section.name)}`;buildForm(item,x);go('editor')}
  function fillFilterOptions(){const s=$('#filterStage'),sec=$('#filterSection');if(!s||!sec)return;s.innerHTML=`<option value="all">${t('allStages')}</option>`;stages.forEach(st=>{const o=document.createElement('option');o.value=st.id;o.textContent=localized(st.name);s.appendChild(o)});s.value=filter.stage;fillSectionFilter()}
  function fillSectionFilter(){const sec=$('#filterSection');if(!sec)return;sec.innerHTML=`<option value="all">${t('allSections')}</option>`;const chosen=filter.stage==='all'?stages:stages.filter(s=>s.id===filter.stage);const names=[...new Set(chosen.flatMap(s=>s.sections.map(x=>x.name)))];names.forEach(n=>{const o=document.createElement('option');o.value=n;o.textContent=localized(n);sec.appendChild(o)});sec.value=filter.section==='all'?'all':filter.section}
  function openFilter(){fillFilterOptions();$('#filterModal').classList.add('show')}
  function closeFilter(){$('#filterModal').classList.remove('show')}
  function openDrawer(){$('#drawer').classList.add('open');$('#drawerScrim').classList.add('show')}
  function closeDrawer(){$('#drawer').classList.remove('open');$('#drawerScrim').classList.remove('show')}
  function exportEstimate(){if(!estimate.length){showToast(t('emptyEstimate'));return}const lines=[t('exportTitle'),''];estimate.forEach((x,i)=>{const options=Object.entries(x.options||{}).map(([k,v])=>`${k}: ${v}`).join(', ');const amount=x.price===null?'—':currency(Number(x.price)*Number(x.quantity));lines.push(`${i+1}. ${x.name} | ${options} | Qty: ${x.quantity} ${x.unit} | Brand: ${x.brand||'—'} | Rate: ${x.price??'—'} | Amount: ${amount}`)});lines.push('',`${t('estimatedTotal')}: ${$('#grandTotal').textContent}`);const text=lines.join('\n');if(navigator.share){navigator.share({title:t('exportTitle'),text}).catch(()=>copyText(text))}else copyText(text)}
  function copyText(text){if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(text).then(()=>showToast(t('exported'))).catch(()=>fallbackCopy(text));else fallbackCopy(text)}
  function fallbackCopy(text){const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();try{document.execCommand('copy');showToast(t('exported'))}catch{showToast(text.slice(0,120))}ta.remove()}
  function currency(n){return '₹ '+(Number.isFinite(n)?n:0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}
  function escapeHTML(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function escapeAttr(s){return escapeHTML(s)}
  function updateEstimateBadge(){$('#estimateCount').textContent=String(estimate.length);$('#navEstimateCount').textContent=String(estimate.length)}
  function calcPower(){const v=Number($('#voltage').value)||0,i=Number($('#current').value)||0;$('#powerResult').textContent=`${(v*i).toLocaleString('en-IN',{maximumFractionDigits:2})} W`}
  function calcOhm(){const p=Number($('#ohmPower').value)||0,v=Number($('#ohmVoltage').value)||0;$('#ohmResult').textContent=`${v?p/v===Infinity?'—':(p/v).toFixed(2):'—'} A`}
  function calcInverter(){const v=Number($('#batteryVoltage').value)||12,p=Number($('#loadWatts').value)||0;$('#inverterResult').textContent=`${(p/v).toFixed(2)} A`}
  function bind(){
    $('#menuBtn').addEventListener('click',openDrawer);$('#closeDrawer').addEventListener('click',closeDrawer);$('#drawerScrim').addEventListener('click',closeDrawer);$('#themeQuick').addEventListener('click',()=>setTheme(theme==='dark'?'light':'dark'));
    $$('[data-go]').forEach(b=>b.addEventListener('click',()=>{const dest=b.dataset.go;go(dest==='stages'?'home':dest)}));$$('[data-back]').forEach(b=>b.addEventListener('click',back));
    $$('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang)));$$('[data-theme]').forEach(b=>b.addEventListener('click',()=>setTheme(b.dataset.theme)));
    $('#openFilter').addEventListener('click',openFilter);$('#openFilter2').addEventListener('click',openFilter);$('#closeFilter').addEventListener('click',closeFilter);$('#filterModal').addEventListener('click',e=>{if(e.target===$('#filterModal'))closeFilter()});$('#filterStage').addEventListener('change',()=>{filter.stage=$('#filterStage').value;filter.section='all';fillSectionFilter()});$('#resetFilter').addEventListener('click',()=>{filter={stage:'all',section:'all'};fillFilterOptions();showToast(t('cleared'))});$('#applyFilter').addEventListener('click',()=>{filter.stage=$('#filterStage').value;filter.section=$('#filterSection').value;closeFilter();if(filter.stage!=='all'){const st=stages.find(s=>s.id===filter.stage);if(st){openStage(st);if(filter.section!=='all'){const sec=st.sections.find(x=>x.name===filter.section);if(sec){currentSection=sec;$('#materialsTitle').textContent=localized(sec.name);renderMaterials();go('materials')}}}}showToast(t('filterApplied'))});
    $('#homeSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){const q=e.target.value.trim().toLowerCase();const match=stages.flatMap(st=>st.sections.map(sec=>({st,sec}))).find(x=>x.sec.items.some(it=>String(it[0]).toLowerCase().includes(q)||localized(String(it[0])).toLowerCase().includes(q)));if(match){currentStage=match.st;currentSection=match.sec;$('#materialsTitle').textContent=localized(match.sec.name);renderMaterials();$('#materialSearch').value=e.target.value;renderMaterials();go('materials')}}});$('#materialSearch').addEventListener('input',renderMaterials);$('#estimateSearch').addEventListener('input',renderEstimate);
    $('#clearForm').addEventListener('click',()=>{if(currentMaterial)buildForm(currentMaterial.item);showToast(t('cleared'))});$('#addMaterial').addEventListener('click',addOrUpdate);
    $('#estimateItems').addEventListener('click',e=>{const edit=e.target.closest('[data-edit]');const del=e.target.closest('[data-delete]');if(edit)editEstimateItem(edit.dataset.edit);if(del){estimate=estimate.filter(x=>x.id!==del.dataset.delete);save();renderEstimate();showToast(t('deleted'))}});
    $('#clearEstimate').addEventListener('click',()=>{if(confirm(t('confirmClear'))){estimate=[];save();renderEstimate();showToast(t('cleared'))}});$('#exportEstimate').addEventListener('click',exportEstimate);
    $('#resetApp').addEventListener('click',resetApp);$('#drawerReset').addEventListener('click',resetApp);$('#aboutApp').addEventListener('click',()=>alert(t('aboutText')));
    $$('[data-calc]').forEach(b=>b.addEventListener('click',()=>{$$('[data-calc]').forEach(x=>x.classList.toggle('active',x===b));['power','ohm','inverter'].forEach(k=>$('#'+k+'Calc').classList.toggle('hidden',k!==b.dataset.calc))}));['voltage','current'].forEach(id=>$('#'+id).addEventListener('input',calcPower));['ohmPower','ohmVoltage'].forEach(id=>$('#'+id).addEventListener('input',calcOhm));['batteryVoltage','loadWatts'].forEach(id=>$('#'+id).addEventListener('input',calcInverter));
    document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('#drawer').classList.contains('open'))closeDrawer();else if($('#filterModal').classList.contains('show'))closeFilter();else back()}});
    window.addEventListener('popstate',()=>back());window.addEventListener('beforeunload',()=>localStorage.setItem(STORE.route,$$('.view.active')[0]?.id||'homeView'));
  }
  function resetApp(){if(!confirm(t('confirmReset')))return;estimate=[];localStorage.removeItem(STORE.items);localStorage.removeItem(STORE.lang);localStorage.removeItem(STORE.theme);lang=cfg.defaultLanguage||'hi';theme=cfg.defaultTheme||'dark';save();setLanguage(lang);setTheme(theme);routeStack=['home'];go('home',false);showToast(t('resetDone'))}
  function init(){normalizeData();applyLanguage();setTheme(theme);bind();renderAll();updateEstimateBadge();calcPower();calcOhm();calcInverter();const requested=localStorage.getItem(STORE.route);if(requested==='estimate'||requested==='calculator'||requested==='settings')go(requested,false);else go('home',false);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
