(()=>{'use strict';
const STORE='sandeepEstimateItems',LANG='sandeepMaterialLang',VIEW='sandeepMaterialView',THEME='sandeepTheme';
const STAGES=[{id:1,no:'STAGE 01',en:'Slab Conduit Installation',hi:'स्लैब कन्ड्यूट इंस्टॉलेशन'},{id:2,no:'STAGE 02',en:'Wall Conduit Installation',hi:'वॉल कन्ड्यूट इंस्टॉलेशन'},{id:3,no:'STAGE 03',en:'Wiring Installation',hi:'वायरिंग इंस्टॉलेशन'},{id:4,no:'STAGE 04',en:'Final Electrical Fittings',hi:'फाइनल इलेक्ट्रिकल फिटिंग्स'},{id:5,no:'STAGE 05',en:'False Ceiling Wiring',hi:'फॉल्स सीलिंग वायरिंग'}];
const LABELS={type:['Type','प्रकार'],subType:['Sub Type','उप प्रकार'],size:['Size','साइज'],shape:['Shape','आकार'],material:['Material','मटेरियल'],conduitSize:['Conduit Size','कन्ड्यूट साइज'],ways:['Ways','वे'],depth:['Depth','गहराई'],hookRod:['Hook Rod','हुक रॉड'],module:['Module','मॉड्यूल'],door:['Door','डोर'],phase:['Phase','फेज'],amp:['Amp','एम्पियर'],colour:['Colour','कलर'],voltage:['Voltage','वोल्टेज'],sensitivity:['Sensitivity','सेंसिटिविटी'],base:['Base','बेस'],wattage:['Wattage','वाटेज'],length:['Length','लंबाई'],mounting:['Mounting','माउंटिंग'],ledDensity:['LED Density','एलईडी डेंसिटी'],supply:['Supply','सप्लाई'],ipRating:['IP Rating','आईपी रेटिंग'],structure:['Structure','स्ट्रक्चर'],diameter:['Diameter','डायमीटर'],cableSize:['Cable Size','केबल साइज'],studSize:['Stud Size','स्टड साइज'],quantity:['Quantity','मात्रा'],unit:['Unit','यूनिट'],brand:['Brand','ब्रांड'],rate:['Rate','रेट']};
let lang=localStorage.getItem(LANG)||'en',view=localStorage.getItem(VIEW)||'grid',estimate=JSON.parse(localStorage.getItem(STORE)||'[]'),stage=1,current=null,currentIndex=-1,state={},carry={};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],save=()=>localStorage.setItem(STORE,JSON.stringify(estimate)),txt=v=>v&&typeof v==='object'?(v[lang]??v.en??v.hi??''):String(v??''),money=n=>'₹'+Number(n||0).toFixed(2),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function activate(e){if(!e)return;$$('.neon-active').forEach(x=>x.classList.remove('neon-active'));e.classList.add('neon-active')}
function label(k){return (LABELS[k]||[k,k])[lang==='hi'?1:0]}
function stageObj(){return STAGES.find(x=>x.id===stage)||STAGES[0]}
function fallback(n){return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 330"><rect width="500" height="330" fill="#07111b"/><circle cx="250" cy="135" r="62" fill="none" stroke="#0ea5e9" stroke-width="7"/><path d="M250 73l-25 70h34l-22 73 61-94h-37z" fill="#facc15"/><text x="250" y="290" text-anchor="middle" fill="#7ea8bb" font-family="Arial" font-size="20">${esc(n)}</text></svg>`)}
function visible(key){return APP_CONFIG.selection[key]!==false}
function show(el,on){if(el)el.style.display=on?'':'none'}
function applyConfig(){show($('.topbar'),APP_CONFIG.home.header);show($('#menuBtn'),APP_CONFIG.home.menu);show($('#langBtn'),APP_CONFIG.home.language);show($('#globalSearchBox'),APP_CONFIG.home.search);show($('[data-ui="homeStages"]'),APP_CONFIG.home.stages);show($('#materialSearchBox'),APP_CONFIG.materials.search);show($('#viewSwitcher'),APP_CONFIG.materials.materialView);[['navHome','home'],['navEstimate','estimate'],['navCalculator','calculator'],['navSettings','settings']].forEach(([u,k])=>show($(`[data-ui="${u}"]`),APP_CONFIG.navigation[k]));show($('#nextMaterial'),APP_CONFIG.selection.nextMaterial);show($('#addEstimate'),APP_CONFIG.selection.addEstimate);show($('#copyEstimate'),APP_CONFIG.estimate.copyEstimate);show($('#printEstimate'),APP_CONFIG.estimate.printEstimate);show($('#shareEstimate'),APP_CONFIG.estimate.shareEstimate)}
function renderStages(){const g=$('#stageGrid');g.innerHTML='';let count=MATERIALS.filter(m=>m.enabled).length;$('#materialCount').textContent=count+' '+(lang==='hi'?'मटेरियल':'materials');STAGES.forEach(s=>{let arr=MATERIALS.filter(m=>m.enabled&&m.stage===s.id);if(!arr.length)return;let b=document.createElement('button');b.className='stage-card';b.innerHTML=`<span class="stage-no">${s.no}</span><h3>${txt(s)}</h3><p>${arr.length} ${lang==='hi'?'मटेरियल':'materials'} • Select to open</p>`;b.onclick=()=>{activate(b);openStage(s.id)};g.appendChild(b)})}
function page(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('#bottomNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));if(id==='estimatePage')renderEstimate();if(id==='settingsPage')renderSettings();if(id==='calculatorPage')renderCalc('power')}
function openStage(id){stage=id;$('#stageLabel').textContent=stageObj().no;$('#stageTitle').textContent=txt(stageObj());$('#materialSearch').value='';renderMaterials();page('materialsPage')}
function renderMaterials(){let g=$('#materialGrid'),q=($('#materialSearch').value||'').toLowerCase();g.className='material-grid '+view;g.innerHTML='';MATERIALS.filter(m=>m.enabled&&m.stage===stage&&(!q||txt(m.name).toLowerCase().includes(q))).forEach(m=>{let b=document.createElement('button');b.className='material-card';b.innerHTML=`${APP_CONFIG.materials.materialImage?`<div class="material-image"><img src="${fallback(txt(m.name))}" alt=""></div>`:''}${APP_CONFIG.materials.materialName?`<div class="material-name">${esc(txt(m.name))}</div>`:''}`;b.onclick=()=>{activate(b);openMaterial(m)};g.appendChild(b)})}
function compatible(m,k,v){return v!==undefined&&v!==''&&Array.isArray(m.options?.[k])&&m.options[k].some(x=>String(txt(x))===String(txt(v)))}
function carryInto(m){let x={};for(const [k,v] of Object.entries(carry))if(k!=='quantity'&&compatible(m,k,v))x[k]=v;return x}
function openMaterial(m){current=m;let list=MATERIALS.filter(x=>x.enabled&&x.stage===m.stage);currentIndex=list.findIndex(x=>x.id===m.id);state=carryInto(m);$('#sheetStage').textContent=stageObj().no;$('#sheetTitle').textContent=txt(m.name);$('#sheetSub').textContent=lang==='hi'?'सभी विकल्प एक ही जगह चुनें':'Select all options in one place';$('#sheetBackdrop').classList.add('open');renderOptions()}
function renderOptions(){let a=$('#optionArea');a.innerHTML='';(current.flow||[]).forEach(k=>{if(current.flowConfig?.[k]?.show===false||!visible(k))return;if(k==='quantity'||k==='rate'){let d=document.createElement('div');d.className='field';d.innerHTML=`<div class="field-label">${label(k)}</div><input id="field-${k}" class="input-field" type="number" min="0" step="any" placeholder="${k==='rate'?'Optional — leave blank for ₹0':'Enter quantity'}" value="${state[k]??''}">`;a.appendChild(d);d.querySelector('input').oninput=e=>state[k]=e.target.value;return}let vals=(current.options?.[k]||[]).filter(v=>current.optionConfig?.[k]?.[v]?.show!==false);if(!vals.length)return;let d=document.createElement('div');d.className='field';d.innerHTML=`<div class="field-label">${label(k)}</div>`;let r=document.createElement('div');r.className='option-row';vals.forEach(v=>{let b=document.createElement('button');b.className='option-btn'+(String(state[k])===String(v)?' selected':'');b.textContent=txt(v);b.onclick=()=>{activate(b);state[k]=v;renderOptions()};r.appendChild(b)});d.appendChild(r);a.appendChild(d)})}
function add(){let qty=Number(state.quantity);if(!Number.isFinite(qty)||qty<=0){alert(lang==='hi'?'कृपया Quantity भरें।':'Please enter Quantity.');return}let rate=state.rate===''||state.rate==null?0:Number(state.rate)||0;estimate.push({id:Date.now()+'-'+Math.random(),materialId:current.id,name:current.name,selections:{...state,quantity:qty,rate},qty,unit:state.unit||'',rate,amount:qty*rate});save();carry={...state,quantity:''};closeSheet();renderEstimate()}
function next(){let list=MATERIALS.filter(x=>x.enabled&&x.stage===current.stage);carry={...state,quantity:''};if(currentIndex+1<list.length)openMaterial(list[currentIndex+1]);else closeSheet()}
function closeSheet(){$('#sheetBackdrop').classList.remove('open')}
function renderEstimate(){let box=$('#estimateList');box.innerHTML='';$('#emptyEstimate').style.display=estimate.length?'none':'block';estimate.forEach(x=>{let tags=Object.entries(x.selections||{}).filter(([k,v])=>!['quantity','rate'].includes(k)&&v!=='').map(([k,v])=>`<span class="tag">${esc(label(k))}: ${esc(txt(v))}</span>`).join('');let d=document.createElement('div');d.className='estimate-card';d.innerHTML=`<div class="estimate-top"><b>${esc(txt(x.name))}</b>${APP_CONFIG.estimate.delete?`<button class="delete-btn">Delete</button>`:''}</div><div class="estimate-meta">${tags}${APP_CONFIG.estimate.quantity?`<span class="tag">Qty: ${x.qty}</span>`:''}${APP_CONFIG.estimate.unit&&x.unit?`<span class="tag">${esc(txt(x.unit))}</span>`:''}</div><div class="estimate-bottom">${APP_CONFIG.estimate.rate?`<span>Rate: ${money(x.rate)}</span>`:''}${APP_CONFIG.estimate.amount?`<b class="amount">${money(x.amount)}</b>`:''}</div>`;d.querySelector('.delete-btn')?.addEventListener('click',()=>{estimate=estimate.filter(y=>y.id!==x.id);save();renderEstimate()});box.appendChild(d)});$('#grandTotal').textContent=money(estimate.reduce((a,x)=>a+Number(x.amount||0),0))}
function estimateText(){return estimate.map((x,i)=>`${i+1}. ${txt(x.name)} | ${Object.entries(x.selections||{}).filter(([k,v])=>v!=='').map(([k,v])=>`${label(k)}: ${txt(v)}`).join(', ')} | Amount: ${money(x.amount)}`).join('\n')+`\n\nGrand Total: ${money(estimate.reduce((a,x)=>a+x.amount,0))}`}
function renderSettings(){let b=$('#settingsList');b.innerHTML='';SETTINGS_ITEMS.forEach(s=>{if(APP_CONFIG.settings[s.id]===false)return;let d=document.createElement('div');d.className='setting-card';if(s.kind==='toggle'){let on=localStorage.getItem('setting_'+s.id)!=='false';d.innerHTML=`<div><b>${s.title}</b><small>${s.desc}</small></div><button class="toggle ${on?'on':''}"><i></i></button>`;d.querySelector('button').onclick=()=>{on=!on;localStorage.setItem('setting_'+s.id,on);d.querySelector('button').classList.toggle('on',on);if(s.id==='darkMode')applyTheme(on?'dark':'light');activate(d.querySelector('button'))}}else{d.innerHTML=`<div><b>${s.title}</b><small>${s.desc}</small></div><button class="cyber small">${s.id==='language'?'Change':s.id==='backup'?'Export':s.id==='reset'?'Reset':'View'}</button>`;d.querySelector('button').onclick=()=>setting(s.id)}b.appendChild(d)})}
function setting(id){if(id==='language')toggleLanguage();if(id==='reset')openResetModal();if(id==='backup'){let blob=new Blob([JSON.stringify(estimate,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='electrofix-estimate.json';a.click();URL.revokeObjectURL(a.href)}if(id==='about')openModal('About',`<div class="profile-card"><div class="profile-logo">⚡</div><div><b>Sandeep ElectroFix</b><small>Powering Your Trust</small><small>Electrical Material Estimate System</small></div></div>`)}
function toggleLanguage(){lang=lang==='en'?'hi':'en';localStorage.setItem(LANG,lang);$('#langBtn').textContent=lang.toUpperCase();renderStages();if(current)renderOptions();renderEstimate();renderSettings();renderCalc('power')}
function applyTheme(t){document.body.classList.toggle('light',t==='light');localStorage.setItem(THEME,t)}
function openModal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modalBackdrop').classList.add('open')}
function openResetModal(){openModal('Clear App Data',`<p style="color:#7895a2;font-size:10px">This will remove the current estimate and saved view preferences.</p><div class="actions"><button id="cancelReset" class="cyber">Cancel</button><button id="confirmReset" class="cyber gold">Reset</button></div>`);$('#cancelReset').onclick=closeModal;$('#confirmReset').onclick=()=>{estimate=[];save();localStorage.removeItem(VIEW);closeModal();renderEstimate();alert('Estimate reset.')}}
function closeModal(){$('#modalBackdrop').classList.remove('open')}
function calcInput(id,labelText,value=''){return `<div class="calc-field"><label>${labelText}</label><input id="${id}" type="number" value="${value}" inputmode="decimal"></div>`}
function renderCalc(type='power'){let box=$('#calcBox');if(type==='power')box.innerHTML=`<h3>Power (P) Calculation</h3><div class="formula">P = V × I</div><div class="calc-fields">${calcInput('cv','Voltage (V)','230')}${calcInput('ci','Current (A)','10')}</div><div class="calc-result"><span>Power (W)</span><b id="cr">2300</b></div><button class="cyber calc-btn" id="calculateBtn">Calculate</button>`;if(type==='current')box.innerHTML=`<h3>Current (I) Calculation</h3><div class="formula">I = P ÷ V</div><div class="calc-fields">${calcInput('cp','Power (W)','2300')}${calcInput('cv','Voltage (V)','230')}</div><div class="calc-result"><span>Current (A)</span><b id="cr">10</b></div><button class="cyber calc-btn" id="calculateBtn">Calculate</button>`;if(type==='voltage')box.innerHTML=`<h3>Voltage (V) Calculation</h3><div class="formula">V = P ÷ I</div><div class="calc-fields">${calcInput('cp','Power (W)','2300')}${calcInput('ci','Current (A)','10')}</div><div class="calc-result"><span>Voltage (V)</span><b id="cr">230</b></div><button class="cyber calc-btn" id="calculateBtn">Calculate</button>`;if(type==='other')box.innerHTML=`<h3>Ohm's Law</h3><div class="formula">V = I × R</div><div class="calc-fields">${calcInput('oi','Current (A)','5')}${calcInput('or','Resistance (Ω)','46')}</div><div class="calc-result"><span>Voltage (V)</span><b id="cr">230</b></div><button class="cyber calc-btn" id="calculateBtn">Calculate</button>`;$('#calculateBtn').onclick=()=>{let r=0;if(type==='power')r=Number($('#cv').value||0)*Number($('#ci').value||0);if(type==='current')r=Number($('#cp').value||0)/Number($('#cv').value||1);if(type==='voltage')r=Number($('#cp').value||0)/Number($('#ci').value||1);if(type==='other')r=Number($('#oi').value||0)*Number($('#or').value||0);$('#cr').textContent=Number.isFinite(r)?r.toFixed(2):'0'}}
function boot(){applyConfig();$('#langBtn').textContent=lang.toUpperCase();applyTheme(localStorage.getItem(THEME)||'dark');renderStages();renderEstimate();renderSettings();renderCalc('power');$('#viewSwitcher button').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.onclick=()=>{activate(b);view=b.dataset.view;if(localStorage.getItem('setting_rememberView')!=='false')localStorage.setItem(VIEW,view);renderMaterials()}});$('#materialSearch').oninput=renderMaterials;$('#globalSearch').oninput=e=>{let q=e.target.value.toLowerCase();if(q){let m=MATERIALS.find(x=>x.enabled&&txt(x.name).toLowerCase().includes(q));if(m)openStage(m.stage)}};$('#langBtn').onclick=e=>{activate(e.currentTarget);toggleLanguage()};$('#menuBtn').onclick=e=>{activate(e.currentTarget);$('#drawerBackdrop').classList.add('open')};$('#closeDrawer').onclick=()=>$('#drawerBackdrop').classList.remove('open');$('#drawerBackdrop').onclick=e=>{if(e.target.id==='drawerBackdrop')$('#drawerBackdrop').classList.remove('open')};$$('.drawer-links button').forEach(b=>b.onclick=()=>{$('#drawerBackdrop').classList.remove('open');page(b.dataset.page)});$('#drawerLang').onclick=toggleLanguage;$('#backToStages').onclick=()=>page('homePage');$('#stageSearchBtn').onclick=()=>$('#materialSearch').focus();$('#closeSheet').onclick=closeSheet;$('#sheetBackdrop').onclick=e=>{if(e.target.id==='sheetBackdrop')closeSheet()};$('#nextMaterial').onclick=e=>{activate(e.currentTarget);next()};$('#addEstimate').onclick=e=>{activate(e.currentTarget);add()};$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};$('#closeModal').onclick=closeModal;$$('#bottomNav button').forEach(b=>b.onclick=()=>{activate(b);page(b.dataset.page)});$('#clearEstimateTop').onclick=()=>{if(confirm('Clear current estimate?')){estimate=[];save();renderEstimate()}};$('#copyEstimate').onclick=async e=>{activate(e.currentTarget);try{await navigator.clipboard.writeText(estimateText());alert('Estimate copied.')}catch{alert(estimateText())}};$('#shareEstimate').onclick=async e=>{activate(e.currentTarget);if(navigator.share)await navigator.share({title:'Sandeep ElectroFix Estimate',text:estimateText()});else{await navigator.clipboard?.writeText(estimateText());alert('Estimate copied.')}};$('#printEstimate').onclick=e=>{activate(e.currentTarget);window.print()};$$('.calc-tabs button').forEach(b=>b.onclick=()=>{$$('.calc-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderCalc(b.dataset.calc)});$$('.quick-calc-grid button').forEach(b=>b.onclick=()=>{if(b.dataset.tool==='ohm'){$$('.calc-tabs button').forEach(x=>x.classList.remove('active'));document.querySelector('[data-calc="other"]').classList.add('active');renderCalc('other');return}alert((b.querySelector('b')?.textContent||'Calculator')+' module is ready for integration.')});$('#loadingScreen').style.display='none'}
window.addEventListener('load',()=>setTimeout(boot,350));
})();
